name: new_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  screen_retriever: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_tts: ^4.0.2

  flutter_lints: ^4.0.0
  animate_do: ^3.3.4
  sqlite3: ^2.4.6
  path: ^1.9.0
  ffi: ^2.1.3
  path_provider: ^2.1.4
  sqlite3_flutter_libs: ^0.5.24
  intl: ^0.19.0
  audioplayers: ^6.1.0
  pdf: ^3.11.0
  printing: ^5.13.3
  bitsdojo_window: ^0.1.6

flutter:

  uses-material-design: true

  assets:
    - assets/homepage.png
    - assets/money.png
    - assets/moneyyours.png
    - assets/shaurma.png
    - assets/pizzas.png
    - assets/burgers.png
    - assets/chickens.png
    - assets/hotdogs.png
    - assets/juices.png

  fonts:
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif_Black.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoSerif_Regular.ttf