name: new_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  screen_retriever: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_tts: ^4.0.2

  flutter_lints: ^4.0.0
  animate_do: ^3.3.4
  sqlite3: ^2.4.6
  path: ^1.9.0
  ffi: ^2.1.3
  path_provider: ^2.1.4
  sqlite3_flutter_libs: ^0.5.24
  intl: ^0.19.0
  audioplayers: ^6.1.0
  pdf: ^3.11.0
  printing: ^5.13.3
  bitsdojo_window: ^0.1.6

flutter:

  uses-material-design: true

  assets:
    - assets/homepage.png
    - assets/money.png
    - assets/moneyyours.png
    - assets/shaurma.png
    - assets/pizzas.png
    - assets/burgers.png
    - assets/chickens.png
    - assets/hotdogs.png
    - assets/juices.png
    - assets/music/001.mp3
    - assets/music/002.mp3
    - assets/music/003.mp3
    - assets/music/004.mp3
    - assets/music/005.mp3
    - assets/music/006.mp3
    - assets/music/007.mp3
    - assets/music/008.mp3
    - assets/music/009.mp3
    - assets/music/010.mp3
    - assets/music/011.mp3
    - assets/music/012.mp3
    - assets/music/013.mp3
    - assets/music/014.mp3
    - assets/music/015.mp3
    - assets/music/016.mp3
    - assets/music/017.mp3
    - assets/music/018.mp3
    - assets/music/019.mp3
    - assets/music/020.mp3
    - assets/music/021.mp3
    - assets/music/022.mp3
    - assets/music/023.mp3
    - assets/music/024.mp3
    - assets/music/025.mp3
    - assets/music/026.mp3
    - assets/music/027.mp3
    - assets/music/028.mp3
    - assets/music/029.mp3
    - assets/music/030.mp3
    - assets/music/031.mp3
    - assets/music/032.mp3
    - assets/music/033.mp3
    - assets/music/034.mp3
    - assets/music/035.mp3
    - assets/music/036.mp3
    - assets/music/037.mp3
    - assets/music/038.mp3
    - assets/music/039.mp3
    - assets/music/040.mp3
    - assets/music/041.mp3
    - assets/music/042.mp3
    - assets/music/043.mp3
    - assets/music/044.mp3
    - assets/music/045.mp3
    - assets/music/046.mp3
    - assets/music/047.mp3
    - assets/music/048.mp3
    - assets/music/049.mp3
    - assets/music/050.mp3
    - assets/music/051.mp3
    - assets/music/052.mp3
    - assets/music/053.mp3
    - assets/music/054.mp3
    - assets/music/055.mp3
    - assets/music/056.mp3
    - assets/music/057.mp3
    - assets/music/058.mp3
    - assets/music/059.mp3
    - assets/music/060.mp3
    - assets/music/061.mp3
    - assets/music/062.mp3
    - assets/music/063.mp3
    - assets/music/064.mp3
    - assets/music/065.mp3
    - assets/music/066.mp3
    - assets/music/067.mp3
    - assets/music/068.mp3
    - assets/music/069.mp3
    - assets/music/070.mp3
    - assets/music/071.mp3
    - assets/music/072.mp3
    - assets/music/073.mp3
    - assets/music/074.mp3
    - assets/music/075.mp3
    - assets/music/076.mp3
    - assets/music/077.mp3
    - assets/music/078.mp3
    - assets/music/079.mp3
    - assets/music/080.mp3
    - assets/music/081.mp3
    - assets/music/082.mp3
    - assets/music/083.mp3
    - assets/music/084.mp3
    - assets/music/085.mp3
    - assets/music/086.mp3
    - assets/music/087.mp3
    - assets/music/088.mp3
    - assets/music/089.mp3
    - assets/music/090.mp3
    - assets/music/091.mp3
    - assets/music/092.mp3
    - assets/music/093.mp3
    - assets/music/094.mp3
    - assets/music/095.mp3
    - assets/music/096.mp3
    - assets/music/097.mp3
    - assets/music/098.mp3
    - assets/music/099.mp3
    - assets/music/100.mp3


  fonts:
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif_Black.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoSerif_Regular.ttf